"""Validation harness — Argus Enterprise Unbound Gateway Phase I cashflow.

Source: ``validation/fixtures/argus_cashflow/Unbound Gateway - Phase I_Cash Flow_*.xls``
(generated by Argus Enterprise 2026.06.01).

Unbound is the cleanest of the 5 Argus exports — zero general vacancy /
credit loss across all 11 years and no rollover until Y11 — which makes it
the deal we pin OpenVal's top-line parity against. The ``ARGUS_PINNED``
golden dict below is the published truth.

Pinning rule (Y1–Y10): every numeric row of the Argus top-line block (PBR,
A&T Vacancy, Free Rent, SBR, TRR, Recoveries, Vacancy + Credit Loss, EGR)
must match the golden number within ``$25`` per cell — enough headroom for
Argus's whole-dollar monthly rounding to compose with float arithmetic on
OpenVal's side, tight enough to catch any real engine drift. Y11 is
excluded — the original lease rolls over there and Argus runs the rollover
with explicit downtime + free rent, while the stub uses
``renewal_probability=1.0`` (instant renewal) to keep the rest of the
horizon stable. Tunable, not a bug.

Run as a script for the human-readable side-by-side:

    .venv/bin/python validation/argus_unbound.py

The pytest test in ``tests/test_argus_unbound.py`` calls
``assert_matches_argus()`` so any engine change that drifts a stabilized
year breaks CI.
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from pathlib import Path

import pandas as pd

from openval import (
    ARGUS_CASHFLOW_ROWS,
    ARGUS_TOP_LINE_ROWS,
    ExpenseStructure,
    Lease,
    MarketLeasingAssumption,
    Property,
    RentStep,
    argus_cashflow_report,
    project_property,
)
from openval.io import read_argus_cashflow_xls


# ----------------------------------------------------------------------
# Golden numbers — extracted from the Argus fixture, pinned for validation
# ----------------------------------------------------------------------
#
# Every list has 11 entries — Y1..Y11 of Argus's fiscal-year roll-up.
# Source: read_argus_cashflow_xls(...).top_line_income("annual"), rounded
# to whole dollars to match Argus's own display precision.
ARGUS_PINNED: dict[str, list[int]] = {
    "Potential Base Rent":
        [4_453_848, 4_531_793, 4_667_751, 4_807_780, 4_952_016, 5_100_580,
         5_253_596, 5_411_201, 5_573_534, 5_740_739, 5_946_861],
    "Absorption & Turnover Vacancy":
        [-1_855_770, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1_007_286],
    "Free Rent":
        [-1_855_770, 0, 0, 0, 0, 0, 0, 0, 0, 0, -654_736],
    "Scheduled Base Rent":
        [742_308, 4_531_793, 4_667_751, 4_807_780, 4_952_016, 5_100_580,
         5_253_596, 5_411_201, 5_573_534, 5_740_739, 4_284_839],
    "Total Rental Revenue":
        [742_308, 4_531_793, 4_667_751, 4_807_780, 4_952_016, 5_100_580,
         5_253_596, 5_411_201, 5_573_534, 5_740_739, 4_284_839],
    "Total Expense Recoveries":
        [880_789, 1_739_184, 1_791_360, 1_845_108, 1_900_464, 1_957_476,
         2_016_192, 2_076_684, 2_138_988, 2_203_152, 1_818_990],
    "Total Tenant Revenue":
        [1_623_097, 6_270_989, 6_459_116, 6_652_888, 6_852_473, 7_058_044,
         7_269_788, 7_487_885, 7_712_522, 7_943_891, 6_103_829],
    "Potential Gross Revenue":
        [1_623_097, 6_270_989, 6_459_116, 6_652_888, 6_852_473, 7_058_044,
         7_269_788, 7_487_885, 7_712_522, 7_943_891, 6_103_829],
    "Total Vacancy & Credit Loss":
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -83_188],
    "Effective Gross Revenue":
        [1_623_097, 6_270_989, 6_459_116, 6_652_888, 6_852_473, 7_058_044,
         7_269_788, 7_487_885, 7_712_522, 7_943_891, 6_020_641],
    # Lower block — opex through bottom-line cash flow.
    "Total Operating Expenses":
        [1_509_927, 1_739_191, 1_791_369, 1_845_107, 1_900_458, 1_957_474,
         2_016_199, 2_076_688, 2_138_984, 2_203_152, 2_182_787],
    "Net Operating Income":
        [113_172, 4_531_798, 4_667_754, 4_807_783, 4_952_015, 5_100_577,
         5_253_596, 5_411_204, 5_573_538, 5_740_739, 3_837_854],
    # Leasing & capital cost rows + downstream cash flow (CFB DS / CFAD)
    # are pinned in the harness but excluded from CI until the stub
    # carries the matching ti_psf / lc_pct / capex_annual / capex_categories
    # inputs (Phase B + stub extension).
    "Tenant Improvements":
        [7_643_630, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2_096_408],
    "Leasing Commissions":
        [4_428_240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2_933_992],
    "Total Leasing Costs":
        [12_071_870, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5_030_400],
    "Non-Leasing Capital Expense":
        [6_522_072, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "Total Capital Expenditures":
        [6_522_072, 0, 57_072, 58_776, 60_540, 62_352, 64_224, 66_156, 68_136, 70_188, 72_288],
    "Total Leasing & Capital Costs":
        [18_593_942, 0, 57_072, 58_776, 60_540, 62_352, 64_224, 66_156, 68_136, 70_188, 5_102_688],
    "Cash Flow Before Debt Service":
        [-18_480_772, 4_531_798, 4_610_682, 4_749_000, 4_891_475, 5_038_218,
         5_189_365, 5_345_048, 5_505_397, 5_670_563, -1_264_834],
    "Cash Flow Available for Distribution":
        [-18_480_772, 4_531_798, 4_610_682, 4_749_000, 4_891_475, 5_038_218,
         5_189_365, 5_345_048, 5_505_397, 5_670_563, -1_264_834],
}

# Window where we expect $-for-$ engine parity. Y1..Y10 inclusive — Y1
# matches once we feed Argus's actual opex (which has a partial-year
# Property Management Fee component during lease-up; OpenVal's recovery
# engine already prorates by occupied months, so the schedule reproduces
# Y1 recoveries exactly). Y11 is excluded — it's partial because of the
# original lease rolling over, which the stub models as instant renewal
# (renewal_probability=1.0) rather than the explicit downtime + free rent
# Argus runs at lease end.
STABILIZED_YEAR_INDEXES: tuple[int, ...] = tuple(range(0, 10))  # Y1..Y10 (0-indexed: 0..9)

# Rows we lock in CI. Section headers and label-only rows are skipped (NaN).
# The lower-block rows below ``Net Operating Income`` (Tenant Improvements,
# Leasing Commissions, Capital Reserves, etc.) live in ``ARGUS_PINNED``
# but aren't in STABILIZED_ROWS yet — they require the stub to carry the
# matching ti_psf / lc_pct / capex_annual inputs, which Phase B will wire.
STABILIZED_ROWS: tuple[str, ...] = (
    "Potential Base Rent",
    "Absorption & Turnover Vacancy",
    "Free Rent",
    "Scheduled Base Rent",
    "Total Rental Revenue",
    "Total Expense Recoveries",
    "Total Tenant Revenue",
    "Potential Gross Revenue",
    "Total Vacancy & Credit Loss",
    "Effective Gross Revenue",
    "Total Operating Expenses",
    "Net Operating Income",
)

# Derived for the lease builder — Argus PBR Y1..Y11 in PSF order.
ARGUS_PBR_BY_YEAR: list[int] = ARGUS_PINNED["Potential Base Rent"]

ACQUISITION = date(2026, 1, 1)
HOLD_YEARS = 11
DOWNTIME_MONTHS = 5  # Y1 A&T vacancy = 5/12 of Y1 PBR
FREE_RENT_MONTHS = 5  # Y1 free rent = 5/12 of Y1 PBR


# Argus Total Operating Expenses Y1..Y11, read directly off the export's
# opex rollup (Real Estate Taxes + Insurance + Property Management Fee +
# CAM). Y1 is materially below Y2 because the Property Management Fee is
# percentage-of-revenue and revenue is depressed during Y1 lease-up
# ($64,923 in Y1 vs. $250,838 in Y2). OpenVal's recovery engine prorates
# whatever schedule we feed it by occupied months — so feeding Argus's
# actual schedule reproduces Argus's recoveries dollar-for-dollar in Y1
# without needing a first-class management-fee model.
ARGUS_OPEX_BY_YEAR: list[int] = [
    1_509_927, 1_739_191, 1_791_369, 1_845_107, 1_900_458, 1_957_474,
    2_016_199, 2_076_688, 2_138_984, 2_203_152, 2_182_787,
]


def _unbound_opex_schedule() -> dict[int, Decimal]:
    """Argus's actual opex schedule (Y1..Y11), keyed by calendar year."""
    return {
        ACQUISITION.year + i: Decimal(str(v))
        for i, v in enumerate(ARGUS_OPEX_BY_YEAR)
    }


def build_stub_property() -> Property:
    """Stub Property mirroring the Argus PBR schedule one-to-one.

    ``area_sf=1`` lets us encode the *annual dollar* PBR directly into
    ``RentStep.annual_psf`` — the projector multiplies psf × area, so with
    area = 1 the value comes through unchanged. This sidesteps any drift
    from inferring an escalation rate vs. matching exact dollar PBR.
    """
    lease_commence = date(ACQUISITION.year, ACQUISITION.month + DOWNTIME_MONTHS, 1)
    lease_term_months = 120  # 10-yr term — leaves a 2-month rollover tail in Y11

    rent_steps: list[RentStep] = []
    # First paying month = lease_commence + free rent. After that, set a step
    # at the start of each calendar year so PBR matches Argus exactly.
    rent_steps.append(
        RentStep(start_date=lease_commence, annual_psf=Decimal(str(ARGUS_PBR_BY_YEAR[0])))
    )
    for y_idx, pbr in enumerate(ARGUS_PBR_BY_YEAR[1:], start=1):
        step_date = date(ACQUISITION.year + y_idx, 1, 1)
        rent_steps.append(RentStep(start_date=step_date, annual_psf=Decimal(str(pbr))))

    mla = MarketLeasingAssumption(
        market_rent_psf=Decimal(str(ARGUS_PBR_BY_YEAR[0])),
        market_rent_growth_pct=Decimal("0.03"),
        new_term_months=lease_term_months,
        rent_escalation_pct=Decimal("0.03"),
        free_rent_months_new=FREE_RENT_MONTHS,
        free_rent_months_renewal=0,
        renewal_probability=Decimal("1.0"),
        downtime_months_new=DOWNTIME_MONTHS,
        expense_structure=ExpenseStructure.NNN,
    )

    lease = Lease(
        suite_id="100",
        tenant_name="Unbound Tenant",
        area_sf=1,
        start_date=lease_commence,
        end_date=date(
            lease_commence.year + lease_term_months // 12,
            lease_commence.month,
            1,
        ),
        base_rent_steps=rent_steps,
        # Free rent on the original lease lives here, not on the MLA — the
        # MLA's free_rent_months_new applies only to speculative rollover
        # segments that the MLA itself spawns.
        free_rent_months=FREE_RENT_MONTHS,
        expense_structure=ExpenseStructure.NNN,
        market_leasing_assumption=mla,
    )

    return Property(
        name="Unbound Gateway - Phase I (OpenVal stub)",
        rentable_sf=1,
        leases=[lease],
        opex_annual=_unbound_opex_schedule(),
        capex_annual={},
        acquisition_date=ACQUISITION,
        acquisition_price=Decimal("1"),  # notional — we're not computing IRR
        hold_years=HOLD_YEARS,
        exit_cap_rate=Decimal("0.05"),
        cpi_series={},
        general_vacancy_pct=Decimal("0"),
        credit_loss_pct=Decimal("0"),
    )


FIXTURE_PATH = (
    Path(__file__).parent
    / "fixtures"
    / "argus_cashflow"
    / "Unbound Gateway - Phase I_Cash Flow_20260601_111332.xls"
)


def run_openval() -> pd.DataFrame:
    """Build the stub property, run ``project_property``, return the full
    Argus cashflow block for OpenVal. Standalone so tests can call it
    without touching the Argus fixture.
    """
    prop = build_stub_property()
    result = project_property(prop)
    return argus_cashflow_report(result, prop)


def _pinned_label_to_row_label(pinned_label: str) -> str:
    """Map an ``ARGUS_PINNED`` key (no indent in the dict for readability) to
    the actual row label in ``ARGUS_CASHFLOW_ROWS`` (indent preserved).
    """
    if pinned_label in ARGUS_CASHFLOW_ROWS:
        return pinned_label
    indented = f"  {pinned_label}"
    if indented in ARGUS_CASHFLOW_ROWS:
        return indented
    raise KeyError(f"{pinned_label!r} not found in ARGUS_CASHFLOW_ROWS")


def pinned_drift() -> pd.DataFrame:
    """Drift (OpenVal − pinned Argus, $) for every row in ARGUS_PINNED
    across all 11 years. Doesn't read the Argus fixture; uses ARGUS_PINNED.
    """
    openval = run_openval()
    years = list(openval.columns)[:11]
    rows = []
    for argus_label, argus_values in ARGUS_PINNED.items():
        row_label = _pinned_label_to_row_label(argus_label)
        ov_row = openval.loc[row_label]
        rows.append((argus_label, [ov_row.iloc[i] - argus_values[i] for i in range(11)]))
    return pd.DataFrame({label: vals for label, vals in rows}, index=years).T


def assert_matches_argus(tolerance: float = 25.0) -> None:
    """Raise ``AssertionError`` if any STABILIZED_ROW × STABILIZED_YEAR cell
    drifts more than ``tolerance`` dollars from the pinned Argus golden.

    Y1 and Y11 are excluded — they represent known lease-up and rollover
    convention gaps that are characterized but not pinned.
    """
    drift = pinned_drift()
    failures: list[str] = []
    for row in STABILIZED_ROWS:
        for y_idx in STABILIZED_YEAR_INDEXES:
            diff = drift.iloc[:, y_idx].loc[row]
            if abs(diff) > tolerance:
                year = drift.columns[y_idx]
                failures.append(f"  {row!r} @ {year}: drift ${diff:,.2f}")
    if failures:
        raise AssertionError(
            "OpenVal has drifted from the pinned Argus Unbound Gateway top-line "
            f"(tolerance=${tolerance:.0f}):\n" + "\n".join(failures)
        )


def main() -> None:
    if not FIXTURE_PATH.exists():
        raise SystemExit(
            f"Argus fixture not found at {FIXTURE_PATH}\n"
            f"Drop the Unbound Gateway export into validation/fixtures/argus_cashflow/."
        )

    cf = read_argus_cashflow_xls(FIXTURE_PATH)
    # Build the full Argus block from the fixture by annualizing every row
    # of the monthly grid (we use top_line_income for income + a manual
    # annual rollup for the lower block, sharing the same fiscal anchoring).
    import pandas as _pd
    n_years = cf.monthly.shape[1] // 12
    argus_full_monthly = cf.monthly.reindex(ARGUS_CASHFLOW_ROWS)
    argus_ann = _pd.concat(
        [
            argus_full_monthly.iloc[:, y * 12 : (y + 1) * 12].sum(axis=1, min_count=1)
            for y in range(n_years)
        ],
        axis=1,
        keys=[f"Year {i + 1}" for i in range(n_years)],
    )

    prop = build_stub_property()
    result = project_property(prop)
    openval_ann = argus_cashflow_report(result, prop)

    # Truncate to the shorter of the two (both should be 11 years).
    n = min(argus_ann.shape[1], openval_ann.shape[1])
    argus_ann = argus_ann.iloc[:, :n]
    openval_ann = openval_ann.iloc[:, :n]
    # Pandas refuses arithmetic across mismatched column labels even when
    # the index positions line up; reuse Argus's "Year N" labels so the
    # subtraction is positional.
    openval_ann.columns = argus_ann.columns

    drift = openval_ann - argus_ann
    drift_pct = drift / argus_ann.replace(0, pd.NA) * 100

    fmt = lambda x: f"{x:>14,.0f}" if x == x and abs(x) >= 1 else (
        "             —" if x != x else "             0"
    )

    print("=" * 96)
    print(f"  Argus (truth) — {cf.property_name}")
    print("=" * 96)
    print(argus_ann.to_string(float_format=fmt))

    print("\n" + "=" * 96)
    print("  OpenVal (stub run)")
    print("=" * 96)
    print(openval_ann.to_string(float_format=fmt))

    print("\n" + "=" * 96)
    print("  Drift (OpenVal − Argus, $)")
    print("=" * 96)
    print(drift.to_string(float_format=fmt))

    print("\n" + "=" * 96)
    print("  Drift % (OpenVal vs. Argus)")
    print("=" * 96)
    print(drift_pct.to_string(float_format=lambda x: f"{x:>14,.2f}%" if x == x else "          n/a"))

    print("\n" + "=" * 96)
    print("  VERDICT — pinned tolerance check (Y1..Y10, STABILIZED_ROWS, ±$25)")
    print("=" * 96)
    try:
        assert_matches_argus(tolerance=25.0)
    except AssertionError as e:
        print("FAIL")
        print(str(e))
    else:
        print(f"PASS — all {len(STABILIZED_ROWS)} rows × {len(STABILIZED_YEAR_INDEXES)} years "
              f"within $25 of Argus golden.")


if __name__ == "__main__":
    main()
