"""Validation harness — Argus Enterprise Telephone Road cashflow.

Source: ``validation/fixtures/argus_cashflow/Telephone Road_Cash Flow_*.xls``
(generated by Argus Enterprise 2026.06.01).

Telephone Road is the second pinned deal — chosen because its shape is
deliberately different from Unbound Gateway:

  * Stabilized at acquisition (Y1 has no A&T vacancy, no free rent — the
    lease is paying full rent from month 1).
  * Two mid-hold rollover events (Y4 and Y9-Y10) with their own downtime
    + free rent + new-tenant TI/LC bills.
  * Non-zero Vacancy Allowance + Credit Loss every year (Argus's
    "General Vacancy" applied on top of A&T).

The simple single-lease stub here covers the **stabilized rows**:
``Potential Base Rent``, the four opex sub-categories, and
``Total Operating Expenses``. These match Argus across the full Y1-Y10
window because they depend only on the rent + opex schedules.

The rollover-driven rows (A&T, Free Rent, SBR, Recoveries during partial-
occupancy years, TI / LC / Capital Reserves, NOI, CFB DS, CFAD, and the
year-varying Vacancy Allowance / Credit Loss) are NOT pinned yet — those
require multi-tenant lease modeling or per-year vacancy overrides which
aren't in the current schema.

Run as a script for the human-readable side-by-side:

    .venv/bin/python validation/argus_telephone_road.py

The pytest test in ``tests/test_argus_telephone_road.py`` calls
``assert_matches_argus()`` so any drift on a pinned row breaks CI.
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from pathlib import Path

import pandas as pd

from openval import (
    ARGUS_CASHFLOW_ROWS,
    ExpenseStructure,
    Lease,
    MarketLeasingAssumption,
    Property,
    RentStep,
    argus_cashflow_report,
    project_property,
)
from openval.io import read_argus_cashflow_xls


ACQUISITION = date(2026, 1, 1)
HOLD_YEARS = 11


# Golden numbers extracted from the Argus Telephone Road export. Each
# list has 11 entries (Y1..Y11). Sub-rows / rows with shape-specific
# rollover behavior aren't included in ARGUS_PINNED — only the rows we
# can realistically pin with the single-lease stub below.
ARGUS_PINNED: dict[str, list[int]] = {
    "Potential Base Rent":
        [4_258_643, 4_412_902, 4_589_221, 4_730_151, 4_850_543, 5_020_313,
         5_196_025, 5_377_884, 5_548_027, 5_670_953, 5_814_971],
    "Real Estate Taxes":
        [1_194_996, 1_230_852, 1_267_776, 1_305_804, 1_344_984, 1_385_328,
         1_426_896, 1_469_700, 1_513_788, 1_559_208, 1_605_984],
    "Insurance":
        [185_004, 190_548, 196_272, 202_152, 208_224, 214_464,
         220_896, 227_532, 234_348, 241_380, 248_628],
    "Property Management Fee":
        [147_272, 152_369, 158_049, 123_664, 158_928, 168_939,
         174_630, 180_510, 173_316, 153_656, 195_717],
    "CAM":
        [153_000, 157_596, 162_312, 167_184, 172_200, 177_372,
         182_688, 188_172, 193_812, 199_632, 205_620],
    "Total Operating Expenses":
        [1_680_272, 1_731_358, 1_784_409, 1_798_814, 1_884_334, 1_946_103,
         2_005_110, 2_065_912, 2_115_276, 2_153_872, 2_255_947],
}

# Pin window: Y1..Y10 (0-indexed 0..9). Y11 partial-year excluded by
# convention; rollover years Y4 / Y9 / Y10 are still pinned because the
# PBR + opex schedules don't depend on rollover (rent steps and opex are
# year-anchored, not lease-event-anchored).
STABILIZED_YEAR_INDEXES: tuple[int, ...] = tuple(range(0, 10))

STABILIZED_ROWS: tuple[str, ...] = (
    "Potential Base Rent",
    "Real Estate Taxes",
    "Insurance",
    "Property Management Fee",
    "CAM",
    "Total Operating Expenses",
)


# Derived for the lease builder — Argus PBR Y1..Y11 in PSF order.
ARGUS_PBR_BY_YEAR: list[int] = ARGUS_PINNED["Potential Base Rent"]


def _telephone_opex_categories() -> dict[str, dict[int, Decimal]]:
    out: dict[str, dict[int, Decimal]] = {}
    for cat in ("Real Estate Taxes", "Insurance",
                "Property Management Fee", "CAM"):
        out[cat] = {
            ACQUISITION.year + i: Decimal(str(v))
            for i, v in enumerate(ARGUS_PINNED[cat])
        }
    return out


def build_stub_property() -> Property:
    """Single-lease stub mirroring Telephone Road's stabilized-at-acquisition
    shape. The lease covers the full projection window (no MLA expansion)
    so PBR + opex track Argus's schedules deterministically.
    """
    lease_start = ACQUISITION
    # Lease term = full hold + 1 year so it never expires inside the
    # projection (Argus's actual rollovers in Y4/Y9 aren't modeled here).
    lease_end = date(ACQUISITION.year + HOLD_YEARS + 1, 1, 1)

    rent_steps = [
        RentStep(
            start_date=date(ACQUISITION.year + i, 1, 1),
            annual_psf=Decimal(str(pbr)),
        )
        for i, pbr in enumerate(ARGUS_PBR_BY_YEAR)
    ]

    mla = MarketLeasingAssumption(
        market_rent_psf=Decimal(str(ARGUS_PBR_BY_YEAR[0])),
        market_rent_growth_pct=Decimal("0.03"),
        new_term_months=120,
        rent_escalation_pct=Decimal("0.03"),
        renewal_probability=Decimal("1.0"),
        downtime_months_new=0,
        expense_structure=ExpenseStructure.NNN,
    )

    lease = Lease(
        suite_id="100",
        tenant_name="Telephone Road Tenant",
        area_sf=1,
        start_date=lease_start,
        end_date=lease_end,
        base_rent_steps=rent_steps,
        expense_structure=ExpenseStructure.NNN,
        market_leasing_assumption=mla,
    )

    return Property(
        name="Telephone Road (OpenVal stub)",
        rentable_sf=1,
        leases=[lease],
        opex_annual={},
        opex_categories=_telephone_opex_categories(),
        capex_annual={},
        acquisition_date=ACQUISITION,
        acquisition_price=Decimal("1"),  # notional — IRR not in scope
        hold_years=HOLD_YEARS,
        exit_cap_rate=Decimal("0.05"),
        cpi_series={},
        general_vacancy_pct=Decimal("0"),
        credit_loss_pct=Decimal("0"),
    )


FIXTURE_PATH = (
    Path(__file__).parent
    / "fixtures"
    / "argus_cashflow"
    / "Telephone Road_Cash Flow_20260601_111516.xls"
)


def run_openval() -> pd.DataFrame:
    prop = build_stub_property()
    result = project_property(prop)
    return argus_cashflow_report(result, prop)


def _pinned_label_to_row_label(pinned_label: str) -> str:
    if pinned_label in ARGUS_CASHFLOW_ROWS:
        return pinned_label
    indented = f"  {pinned_label}"
    if indented in ARGUS_CASHFLOW_ROWS:
        return indented
    raise KeyError(f"{pinned_label!r} not found in ARGUS_CASHFLOW_ROWS")


def pinned_drift() -> pd.DataFrame:
    openval = run_openval()
    years = list(openval.columns)[:11]
    rows = []
    for argus_label, argus_values in ARGUS_PINNED.items():
        row_label = _pinned_label_to_row_label(argus_label)
        ov_row = openval.loc[row_label]
        rows.append((argus_label, [ov_row.iloc[i] - argus_values[i] for i in range(11)]))
    return pd.DataFrame({label: vals for label, vals in rows}, index=years).T


def assert_matches_argus(tolerance: float = 25.0) -> None:
    drift = pinned_drift()
    failures: list[str] = []
    for row in STABILIZED_ROWS:
        for y_idx in STABILIZED_YEAR_INDEXES:
            diff = drift.iloc[:, y_idx].loc[row]
            if abs(diff) > tolerance:
                year = drift.columns[y_idx]
                failures.append(f"  {row!r} @ {year}: drift ${diff:,.2f}")
    if failures:
        raise AssertionError(
            "OpenVal has drifted from the pinned Argus Telephone Road numbers "
            f"(tolerance=${tolerance:.0f}):\n" + "\n".join(failures)
        )


def main() -> None:
    if not FIXTURE_PATH.exists():
        raise SystemExit(f"Argus fixture not found at {FIXTURE_PATH}")

    cf = read_argus_cashflow_xls(FIXTURE_PATH)
    n_years = cf.monthly.shape[1] // 12
    argus_full_monthly = cf.monthly.reindex(ARGUS_CASHFLOW_ROWS)
    argus_ann = pd.concat(
        [
            argus_full_monthly.iloc[:, y * 12 : (y + 1) * 12].sum(axis=1, min_count=1)
            for y in range(n_years)
        ],
        axis=1,
        keys=[f"Year {i + 1}" for i in range(n_years)],
    )

    prop = build_stub_property()
    result = project_property(prop)
    openval_ann = argus_cashflow_report(result, prop)

    n = min(argus_ann.shape[1], openval_ann.shape[1])
    argus_ann = argus_ann.iloc[:, :n]
    openval_ann = openval_ann.iloc[:, :n]
    openval_ann.columns = argus_ann.columns

    drift = openval_ann - argus_ann

    fmt = lambda x: f"{x:>14,.0f}" if x == x and abs(x) >= 1 else (
        "             —" if x != x else "             0"
    )

    # Just print drift to keep output focused.
    print("=" * 96)
    print("  Telephone Road — OpenVal − Argus drift ($) — pinned rows only")
    print("=" * 96)
    drift_pinned = drift.loc[[_pinned_label_to_row_label(r) for r in STABILIZED_ROWS]]
    print(drift_pinned.iloc[:, :10].to_string(float_format=fmt))

    print("\n" + "=" * 96)
    print("  VERDICT — pinned tolerance check (Y1..Y10, STABILIZED_ROWS, ±$25)")
    print("=" * 96)
    try:
        assert_matches_argus(tolerance=25.0)
    except AssertionError as e:
        print("FAIL")
        print(str(e))
    else:
        print(f"PASS — all {len(STABILIZED_ROWS)} rows × {len(STABILIZED_YEAR_INDEXES)} years "
              f"within $25 of Argus golden.")


if __name__ == "__main__":
    main()
